export type Theme = "Australian context" | "Adoption & readiness" | "Delay mitigation";

export type Article = {
  slug: string;
  title: string;
  authors: string;
  year: number;
  journal: string;
  citation: string;
  doi: string;
  theme: Theme;
  type: "Empirical study" | "Review";
  access: "Open access" | "CQU full text" | "Publisher access";
  summary: string;
  findings: string[];
  relevance: string;
  caveat: string;
  tags: string[];
  fullTextUrl?: string;
  libraryUrl?: string;
};

export const articles: Article[] = [
  {
    slug: "khan-construction-smes-ai-adoption",
    title: "Knowledge Management-Based Artificial Intelligence (AI) Adoption in Construction SMEs: The Moderating Role of Knowledge Integration",
    authors: "Ali Nawaz Khan, Khalid Mehmood & Mohsin Ali Soomro",
    year: 2024,
    journal: "IEEE Transactions on Engineering Management",
    citation: "71, 10874–10884",
    doi: "10.1109/TEM.2024.3403981",
    theme: "Adoption & readiness",
    type: "Empirical study",
    access: "CQU full text",
    summary: "A two-wave survey of 422 Pakistani construction SMEs tests how openness to innovation and knowledge practices relate to intention to use AI and actual use six months later.",
    findings: ["Openness to innovation was associated with greater perceived AI knowledge; that knowledge was associated with higher performance expectancy, but not significantly with effort expectancy.", "Performance expectancy was positively associated with intention to use AI, and intention was associated with actual use.", "Knowledge integration strengthened the relationship between intention and actual use."],
    relevance: "Use it to define knowledge-sharing, data practices and integration as potential readiness dimensions for Queensland construction SMEs.",
    caveat: "The sample is from Pakistan. Its relationships may differ for regional Queensland firms; the survey design also does not establish causation.",
    tags: ["construction SMEs", "knowledge integration", "AI adoption"],
    libraryUrl: "https://cqu.primo.exlibrisgroup.com/discovery/fulldisplay?docid=cdi_crossref_primary_10_1109_TEM_2024_3403981&context=PC&vid=61CQU_INST:61CQU&lang=en_US",
  },
  {
    slug: "siriwardhana-construction-4-australia",
    title: "Construction 4.0 in Australia: Evaluating technological implementation, organisational adaptation and skills development",
    authors: "Senuri Siriwardhana, Robert Moehler & Yihai Fang",
    year: 2025,
    journal: "Journal of Innovation & Knowledge",
    citation: "10(6), 100822",
    doi: "10.1016/j.jik.2025.100822",
    theme: "Australian context",
    type: "Empirical study",
    access: "Open access",
    summary: "Interviews with 23 Australian construction industry experts examine how technology, organisational practices, infrastructure and workforce skills shape Construction 4.0 adoption.",
    findings: ["AI and several other advanced tools remain less used than established technologies such as BIM and drones.", "Digital skills, fragmented integration and resistance to change constrain adoption.", "Regional connectivity and SME investment capacity matter to technology readiness."],
    relevance: "A priority source for adapting international AI-readiness frameworks to regional Queensland conditions.",
    caveat: "It studies Construction 4.0 broadly, rather than AI project-management tools or delay outcomes specifically.",
    tags: ["Australia", "regional", "skills", "infrastructure"],
    fullTextUrl: "https://doi.org/10.1016/j.jik.2025.100822",
  },
  {
    slug: "perera-australian-construction-technology-uptake",
    title: "Uptake of industry 4.0 technologies in Australian construction firms",
    authors: "C. Savindi Ranthika Perera, Valerie Francis & Shang Gao",
    year: 2026,
    journal: "Engineering, Construction and Architectural Management",
    citation: "33(3), 2071–2088",
    doi: "10.1108/ECAM-07-2024-0976",
    theme: "Australian context",
    type: "Empirical study",
    access: "Publisher access",
    summary: "Using 19 interviews, this Australian study investigates applications, maturity and interest in 14 Construction 4.0 technologies across construction firms.",
    findings: ["Technology use clusters around data capture, communication, analysis, visualisation and off-site construction.", "Firms favour mature technologies with proven value; some innovators experiment while others wait for wider adoption."],
    relevance: "Helps distinguish awareness or interest from actual implementation when measuring SME readiness.",
    caveat: "The article covers a range of digital technologies, so its findings should not be treated as AI-specific adoption rates.",
    tags: ["Australia", "technology maturity", "adoption interest"],
  },
  {
    slug: "soltani-industry-4-australia",
    title: "The State of Industry 4.0 in the Australian Construction Industry: An Examination of Industry and Academic Point of View",
    authors: "Sahar Soltani, Duncan Maxwell & Ali Rashidi",
    year: 2023,
    journal: "Buildings",
    citation: "13(9), 2324",
    doi: "10.3390/buildings13092324",
    theme: "Australian context",
    type: "Empirical study",
    access: "Open access",
    summary: "A literature and desktop review, followed by workshops, explores drivers and barriers to Industry 4.0 in Australian construction.",
    findings: ["Adoption depends on human and organisational factors alongside technology.", "Data practices, integration, education and training are important enablers."],
    relevance: "Provides Australian context and candidate interview or survey themes for the readiness assessment.",
    caveat: "Industry 4.0 is broader than AI-enabled delay management.",
    tags: ["Australia", "Construction 4.0", "training"],
    fullTextUrl: "https://www.mdpi.com/2075-5309/13/9/2324",
  },
  {
    slug: "regona-ai-technologies-australia",
    title: "Artificial Intelligent Technologies for the Construction Industry: How Are They Perceived and Utilized in Australia?",
    authors: "Massimo Regona, Tan Yigitcanlar, Bo Xia & Rita Yi Man Li",
    year: 2022,
    journal: "Journal of Open Innovation: Technology, Market, and Complexity",
    citation: "8(1), 16",
    doi: "10.3390/joitmc8010016",
    theme: "Australian context",
    type: "Empirical study",
    access: "Open access",
    summary: "Examines Australian perceptions of AI technologies in construction and the prospects and constraints that may affect uptake.",
    findings: ["AI possibilities extend across the construction project lifecycle.", "Knowledge and understanding of AI remain important constraints on adoption."],
    relevance: "Useful background for questions about familiarity, trust and perceived value of AI among local SMEs.",
    caveat: "Its perception-focused evidence does not directly measure firm-level readiness or delay mitigation.",
    tags: ["Australia", "perceptions", "AI awareness"],
    fullTextUrl: "https://www.mdpi.com/2199-8531/8/1/16",
  },
  {
    slug: "shang-ai-project-management-adoption",
    title: "Prospects, drivers of and barriers to artificial intelligence adoption in project management",
    authors: "Shang Gao, Sui Pheng Low & Xin Ying Valen Lim",
    year: 2023,
    journal: "Built Environment Project and Asset Management",
    citation: "13(5), 629–645",
    doi: "10.1108/BEPAM-12-2022-0195",
    theme: "Adoption & readiness",
    type: "Empirical study",
    access: "CQU full text",
    summary: "A mixed-methods study of project-management professionals' perceptions of AI adoption in the built environment.",
    findings: ["Leadership support, organisational readiness and expected productivity gains are leading adoption drivers.", "High implementation and maintenance costs, weak senior support and limited AI skills are leading barriers."],
    relevance: "Translate its adoption factors into questions for SME owners and project managers.",
    caveat: "Its professionals were surveyed outside Australia, and the sample is not limited to SMEs.",
    tags: ["project management", "leadership", "cost", "skills"],
  },
  {
    slug: "althoey-conversational-ai-small-projects",
    title: "Assessment of complexities in implementation of conversational AI for the digital transformation of small construction project",
    authors: "Fadi Althoey, Muhamamd Sajjad, Moustafa Houda & A. Waqar",
    year: 2025,
    journal: "Ain Shams Engineering Journal",
    citation: "16(6), 103370",
    doi: "10.1016/j.asej.2025.103370",
    theme: "Adoption & readiness",
    type: "Empirical study",
    access: "Open access",
    summary: "A survey of 244 construction experts tests economic, personal and technical barriers to using conversational AI on small projects.",
    findings: ["Implementation cost was the strongest reported barrier in the study's model.", "Security concerns and technical complexity were also significant barriers."],
    relevance: "Especially useful for a small-firm questionnaire about affordability, data security and usability.",
    caveat: "It addresses conversational AI and small projects, which are not identical to SME project-management platforms.",
    tags: ["small projects", "cost", "security", "technical complexity"],
    fullTextUrl: "https://doi.org/10.1016/j.asej.2025.103370",
  },
  {
    slug: "badghish-sme-ai-toe",
    title: "Artificial Intelligence Adoption by SMEs to Achieve Sustainable Business Performance: Application of Technology–Organization–Environment Framework",
    authors: "Saeed Badghish & Yasir Ali Soomro",
    year: 2024,
    journal: "Sustainability",
    citation: "16(5), 1864",
    doi: "10.3390/su16051864",
    theme: "Adoption & readiness",
    type: "Empirical study",
    access: "Open access",
    summary: "A survey of SMEs across six Saudi Arabian sectors uses the technology–organisation–environment (TOE) framework to examine AI adoption and business performance.",
    findings: ["Relative advantage, compatibility, human capital, demand and government support were associated with adoption.", "The authors found meaningful differences between small and medium-sized firms."],
    relevance: "Offers a ready-made structure for a Queensland SME readiness model and size-sensitive analysis.",
    caveat: "Its sample spans sectors and is outside Australia; construction-specific variables need to be added.",
    tags: ["SMEs", "TOE framework", "firm size"],
    fullTextUrl: "https://www.mdpi.com/2071-1050/16/5/1864",
  },
  {
    slug: "wuni-integrated-digital-delivery-barriers",
    title: "Critical barriers to the adoption of integrated digital delivery in the construction industry",
    authors: "Ibrahim Yahaya Wuni, Derek Asante Abankwa, Kerim Koc, Selorm Emmanuel Adukpo & Maxwell Fordjour Antwi-Afari",
    year: 2024,
    journal: "Journal of Building Engineering",
    citation: "83, 108474",
    doi: "10.1016/j.jobe.2024.108474",
    theme: "Adoption & readiness",
    type: "Empirical study",
    access: "Open access",
    summary: "A Hong Kong construction survey examines barriers to integrated digital delivery across connected data, platforms and project stakeholders.",
    findings: ["Skill gaps, frequent model updates, investment, interoperability and limited budgets ranked among critical barriers.", "Financial, organisational, technical, data and stakeholder issues interact rather than operating separately."],
    relevance: "Helps test whether an SME can connect an AI tool to the project data and workflows it already uses.",
    caveat: "The technology studied is integrated digital delivery rather than AI itself.",
    tags: ["interoperability", "budget", "digital delivery"],
    fullTextUrl: "https://discovery.ucl.ac.uk/id/eprint/10185364/",
  },
  {
    slug: "lagos-ml-schedule-performance",
    title: "Predicting construction schedule performance with last planner system and machine learning",
    authors: "Camilo I. Lagos, Rodrigo F. Herrera, Alejandro F. Mac Cawley & Luis F. Alarcón",
    year: 2024,
    journal: "Automation in Construction",
    citation: "167, 105716",
    doi: "10.1016/j.autcon.2024.105716",
    theme: "Delay mitigation",
    type: "Empirical study",
    access: "Publisher access",
    summary: "Develops and evaluates machine-learning models using Last Planner System indicators to predict construction schedule outcomes during project execution.",
    findings: ["Early schedule predictions can act as warnings that support intervention.", "Combining planning-system indicators with schedule measures improves the information available for prediction."],
    relevance: "A strong example of the actual delay-mitigation function an AI-enabled tool could provide.",
    caveat: "A predictive model requires consistent project data; feasibility for data-poor regional SMEs remains a separate question.",
    tags: ["schedule prediction", "Last Planner System", "machine learning"],
  },
  {
    slug: "alsulamy-construction-delay-risk",
    title: "Predicting construction delay risks in Saudi Arabian projects: A comparative analysis of CatBoost, XGBoost, and LGBM",
    authors: "Saleh Alsulamy",
    year: 2025,
    journal: "Expert Systems with Applications",
    citation: "268, 126268",
    doi: "10.1016/j.eswa.2024.126268",
    theme: "Delay mitigation",
    type: "Empirical study",
    access: "Publisher access",
    summary: "Compares three machine-learning algorithms for classifying construction delay risk and time-overrun severity.",
    findings: ["The study reports promising prediction performance, with LightGBM outperforming the other tested models in its setting.", "Risk classification could help prioritise project-management attention before delays escalate."],
    relevance: "Supports the rationale for AI delay-risk alerts and suggests possible tool evaluation criteria.",
    caveat: "The study uses a small Saudi Arabian dataset; model performance should not be assumed for Queensland projects.",
    tags: ["delay risk", "predictive analytics", "LightGBM"],
  },
  {
    slug: "taboada-ai-enabled-project-management-review",
    title: "Artificial Intelligence Enabled Project Management: A Systematic Literature Review",
    authors: "Ianire Taboada, Abouzar Daneshpajouh, Nerea Toledo & Tharaka de Vass",
    year: 2023,
    journal: "Applied Sciences",
    citation: "13(8), 5014",
    doi: "10.3390/app13085014",
    theme: "Delay mitigation",
    type: "Review",
    access: "Open access",
    summary: "A systematic review maps AI techniques and project-management applications across performance domains, including planning, measurement and uncertainty.",
    findings: ["Machine learning is prominent in the reviewed project-management literature.", "Forecasting and decision support are common applications, especially for construction projects.", "Real-world project-management implementation was still at an early stage in the literature reviewed."],
    relevance: "Use this as a map of AI-enabled project-management functions and to frame the research gap.",
    caveat: "The search ended in 2022; pair it with newer studies in this library.",
    tags: ["systematic review", "project management", "forecasting"],
    fullTextUrl: "https://www.mdpi.com/2076-3417/13/8/5014",
  },
];

export const themes: Theme[] = ["Australian context", "Adoption & readiness", "Delay mitigation"];

export const articleBySlug = (slug: string) => articles.find((article) => article.slug === slug);
